[package]
name = "rsadv_control_cli"
version = "0.2.0"
edition = "2021"

[dependencies]
rsadv_control = { version = "0.2.0", path = "../rsadv_control" }

clap = { version = "4.5.46", features = ["derive"] }
thiserror = "1.0.58"
pretty_env_logger = "0.5.0"
log = "0.4.27"
