name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  RUST_BACKTRACE: full

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup update stable --no-self-update && rustup default stable
    - run: rustup component add rustfmt
    - run: cargo fmt --all --check

  stable:
    strategy:
      matrix:
        os:
        - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - run: rustup update stable --no-self-update && rustup default stable
    - run: cargo test --workspace

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup update stable --no-self-update && rustup default stable
    - run: cargo doc --no-deps --all-features

    
